[package]
name = "echoes_prelude"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["games"]
description = "A cross-platform 2D platformer RPG."
keywords = ["game"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lukexor/echos-prelude.git"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[package.metadata]
msrv = "1.65.0"

[features]
default = ["vulkan"]
hot_reload = ["dep:hot-lib-reloader"]
vulkan = ["pix-engine/vulkan"]
opengl = ["pix-engine/opengl"]

[dependencies]
anyhow = { workspace = true }
pix-engine = { workspace = true }
env_logger = { workspace = true }
hot-lib-reloader = { version = "0.6.4", optional = true }
log = { workspace = true }
echoes_prelude_lib = { path = "lib" }
tokio = { workspace = true }
winit = { workspace = true }

[profile.dev]
debug-assertions = true
opt-level = 1

[workspace]
resolver = "2"
members = [
    "engine",
    "lib",
]

[workspace.dependencies]
anyhow = "1.0.66"
pix-engine = { path = "engine" }
env_logger = "0.10.0"
derive_more = "0.99.17"
log = "0.4.7"
tokio = { version = "1.23.0", features = ["full"] }
winit = "0.27.5"
