[package]
name = "echoes_engine"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["game-development", "game-engines", "graphics", "gui", "rendering"]
description = "A cross-platform, hot-reloadable graphics/game engine for simple games, visualizations, and graphics applications."
keywords = ["game", "engine", "graphics", "ui", "gui", "rendering"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lukexor/echos-prelude.git"
version = "0.1.0"
edition = "2021"

[package.metadata]
msrv = "1.65.0"

[lib]
crate-type = ["rlib", "dylib"]

[features]
default = []
vulkan = ["dep:ash"]
opengl = []

[dependencies]
anyhow = { workspace = true }
ash = { version = "0.37.1", features = ["linked"], optional = true }
cfg-if = "1.0.0"
derive_more = "0.99.17"
env_logger = { workspace = true }
log = { workspace = true }
png = "0.17.6"
tobj = "3.2.3"
tokio = { version = "1.23.0", features = ["full"] }
winit = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
metal = "0.24.0"
objc  = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.5", features = ["windef", "libloaderapi"] }
